# Generated by Django 6.1.1 on 2026-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
