# Generated by Django 6.1.1 on 2026-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=100)),
                ('courses_code', models.CharField(max_length=20, unique=True)),
                ('during', models.CharField(max_length=50)),
                ('total_credits', models.PositiveIntegerField(default=0)),
                ('fee_par_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
